StockManagement.MVC/Models/GraphicsCardViewModel.cs
using StockManagement.Shared.Models;
using StockManagement.Shared.Repos;
using System.ComponentModel.DataAnnotations;

namespace StockManagement.MVC.Models
{
    public class GraphicsCardViewModel
    {
        public GraphicsCardViewModel(int ID, string Name, string Type, int? Stock, double? Price, int VRAM, int CudaCores)
        {
            this.ID = ID;
            this.Name = Name;
            this.Type = Type;
            this.Stock = Stock;
            this.Price = Price;
            this.VRAM = VRAM;
            this.CudaCores = CudaCores;
        }

        public int ID { get; set; }

        public string Name { get; set; }

        public string Type { get; set; }

        public int? Stock { get; set; }

        [DisplayFormat(DataFormatString = "{0:#,##0.##}")]
        public double? Price { get; set; }

        public int VRAM { get; set; }

        [DisplayFormat(DataFormatString = "{0:#,##0}")]
        public int CudaCores { get; set; }
    }
}

StockManagement.MVC/Models/LaptopViewModel.cs
using StockManagement.Shared.Models;
using StockManagement.Shared.Repos;
using System.ComponentModel.DataAnnotations;

namespace StockManagement.MVC.Models
{
    public class LaptopViewModel
    {
        public LaptopViewModel(int ID, string Name, string Type, int? Stock, double? Price, double ScreenSize, int RAM, int Storage)
        {
            this.ID = ID;
            this.Name = Name;
            this.Type = Type;
            this.Stock = Stock;
            this.Price = Price;
            this.ScreenSize = ScreenSize;
            this.RAM = RAM;
            this.Storage = Storage;
        }

        public int ID { get; set; }

        public string Name { get; set; }

        public string Type { get; set; }

        public int? Stock { get; set; }

        [DisplayFormat(DataFormatString = "{0:#,##0.##}")]
        public double? Price { get; set; }

        public double ScreenSize { get; set; }

        public int RAM { get; set; }

        public int Storage { get; set; }
    }
}

StockManagement.MVC/Controllers/DeleteItemController.cs
using Microsoft.AspNetCore.Mvc;
using StockManagement.MVC.Models;
using StockManagement.Shared.Models;
using StockManagement.Shared.Repos;

namespace StockManagement.MVC.Controllers
{
    public class DeleteItemController : Controller
    {
        private readonly IItemsRepository<Laptop> _laptopRepository;
        private readonly IItemsRepository<GraphicsCard> _graphicsCardRepository;

        public DeleteItemController(IItemsRepository<Laptop> laptopRepository, IItemsRepository<GraphicsCard> graphicsCardRepository)
        {
            _laptopRepository = laptopRepository;
            _graphicsCardRepository = graphicsCardRepository;
        }

        [Route("/DeleteItemConfirmation/{itemId}")]
        public IActionResult DeleteItemView(int itemId)
        {
            GraphicsCard? graphicsCard = _graphicsCardRepository.GetItem(itemId);
            Laptop? laptop = _laptopRepository.GetItem(itemId);
            if (graphicsCard != null)
            {
                DeleteItemViewModel deleteItemViewModel = new(null, graphicsCard);
                return View(deleteItemViewModel);
            }
            else if (laptop != null)
            {
                DeleteItemViewModel deleteItemViewModel = new(laptop, null);
                return View(deleteItemViewModel);
            }
            else
            {
                return NotFound();
            }
        }

        public IActionResult DeleteItem(int itemId)
        {
            GraphicsCard? graphicsCard = _graphicsCardRepository.GetItem(itemId);
            Laptop? laptop = _laptopRepository.GetItem(itemId);
            if (graphicsCard != null)
            {
                var isGraphicsCardDeleted = _graphicsCardRepository.DeleteItem(itemId);
                if (isGraphicsCardDeleted)
                {
                    return RedirectToAction("Index", "Home", new { itemRecentlyAdded = false, itemRecentlyEdited = false, itemRecentlyDeleted = true });
                }
                else
                {
                    return BadRequest();
                }
            }
            else if (laptop != null)
            {
                var isLaptopDeleted = _laptopRepository.DeleteItem(itemId);
                if (isLaptopDeleted)
                {
                    return RedirectToAction("Index", "Home", new { itemRecentlyAdded = false, itemRecentlyEdited = false, itemRecentlyDeleted = true });
                }
                else
                {
                    return BadRequest();
                }
            }
            else
            {
                return BadRequest();
            }
        }
    }
}

StockManagement.MVC/Controllers/EditGraphicsCardController.cs
using Microsoft.AspNetCore.Mvc;
using StockManagement.MVC.Models;
using StockManagement.Shared.Models;
using StockManagement.Shared.Repos;

namespace StockManagement.MVC.Controllers
{
    public class EditGraphicsCardController : Controller
    {
        private readonly IItemsRepository<GraphicsCard> _graphicsCardRepository;

        public EditGraphicsCardController(IItemsRepository<GraphicsCard> graphicsCardRepository)
        {
            _graphicsCardRepository = graphicsCardRepository;
        }

        [Route("/EditGraphicsCard/{graphicsCardId}")]
        public IActionResult EditGraphicsCardView(int graphicsCardId)
        {
            GraphicsCard? graphicsCard = _graphicsCardRepository.GetItem(graphicsCardId);
            if (graphicsCard != null)
            {
                EditGraphicsCardViewModel editGraphicsCardViewModel = new(graphicsCard.ID, graphicsCard.Name, graphicsCard.Type, graphicsCard.Stock,
                    graphicsCard.Price, graphicsCard.VRAM, graphicsCard.CudaCores);
                return View(editGraphicsCardViewModel);
            }
            else
            {
                return NotFound();
            }
        }

        public IActionResult EditGraphicsCard(int ID, string Name, string Type, int? Stock, double? Price, int VRAM, int CudaCores)
        {
            GraphicsCard exampleItem = new(ID, Name, Type, Stock, Price, VRAM, CudaCores);
            GraphicsCard? editedItem = _graphicsCardRepository.EditItem(exampleItem, ID);
            if (editedItem != null && editedItem.Name == Name && editedItem.Stock == Stock && editedItem.Price == Price && editedItem.VRAM == VRAM && editedItem.CudaCores == CudaCores)
            {
                return RedirectToAction("Index", "Home", new { itemRecentlyAdded = false, itemRecentlyEdited = true, itemRecentlyDeleted = false });
            }
            else
            {
                return BadRequest();
            }
        }
    }
}

StockManagement.MVC/Controllers/EditLaptopController.cs
using Microsoft.AspNetCore.Mvc;
using StockManagement.MVC.Models;
using StockManagement.Shared.Models;
using StockManagement.Shared.Repos;

namespace StockManagement.MVC.Controllers
{
    public class EditLaptopController : Controller
    {
        private readonly IItemsRepository<Laptop> _laptopRepository;

        public EditLaptopController(IItemsRepository<Laptop> laptopRepository)
        {
            _laptopRepository = laptopRepository;
        }

        [Route("/EditLaptop/{laptopId}")]
        public IActionResult EditLaptopView(int laptopId)
        {
            Laptop? laptop = _laptopRepository.GetItem(laptopId);
            if (laptop != null)
            {
                EditLaptopViewModel editLaptopViewModel = new(laptop.ID, laptop.Name, laptop.Type, laptop.Stock,
                    laptop.Price, laptop.ScreenSize, laptop.RAM, laptop.Storage);
                return View(editLaptopViewModel);
            }
            else
            {
                return NotFound();
            }
        }

        public IActionResult EditLaptop(int ID, string Name, string Type, int? Stock, double? Price, double ScreenSize, int RAM, int Storage)
        {
            Laptop exampleItem = new(ID, Name, Type, Stock, Price, ScreenSize, RAM, Storage);
            Laptop? editedItem = _laptopRepository.EditItem(exampleItem, ID);
            if (editedItem != null && editedItem.Name == Name && editedItem.Stock == Stock && editedItem.Price == Price
                && editedItem.ScreenSize == ScreenSize && editedItem.RAM == RAM && editedItem.Storage == Storage)
            {
                return RedirectToAction("Index", "Home", new { itemRecentlyAdded = false, itemRecentlyEdited = true, itemRecentlyDeleted = false });
            }
            else
            {
                return BadRequest();
            }
        }
    }
}

StockManagement.MVC/Controllers/GraphicsCardController.cs
using Microsoft.AspNetCore.Mvc;
using StockManagement.MVC.Models;
using StockManagement.Shared.Models;
using StockManagement.Shared.Repos;

namespace StockManagement.MVC.Controllers
{
    public class GraphicsCardController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IItemsRepository<GraphicsCard> _graphicsCardRepository;

        public GraphicsCardController(ILogger<HomeController> logger, IItemsRepository<GraphicsCard> graphicsCardRepository)
        {
            _logger = logger;
            _graphicsCardRepository = graphicsCardRepository;
        }

        [Route("/GraphicsCardDetails/{graphicsCardId}")]
        public IActionResult GraphicsCardView(int graphicsCardId)
        {
            GraphicsCard? graphicsCard = _graphicsCardRepository.GetItem(graphicsCardId);
            if (graphicsCard != null)
            {
                GraphicsCardViewModel graphicsCardViewModel = new(graphicsCard.ID, graphicsCard.Name, graphicsCard.Type, graphicsCard.Stock,
                    graphicsCard.Price, graphicsCard.VRAM, graphicsCard.CudaCores);
                return View(graphicsCardViewModel);
            }
            else
            {
                return NotFound();
            }
        }
    }
}

StockManagement.MVC/Controllers/LaptopController.cs
using Microsoft.AspNetCore.Mvc;
using StockManagement.MVC.Models;
using StockManagement.Shared.Models;
using StockManagement.Shared.Repos;

namespace StockManagement.MVC.Controllers
{
    public class LaptopController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IItemsRepository<Laptop> _laptopRepository;

        public LaptopController(ILogger<HomeController> logger, IItemsRepository<Laptop> laptopRepository)
        {
            _logger = logger;
            _laptopRepository = laptopRepository;
        }

        [Route("/LaptopDetails/{laptopId}")]
        public IActionResult LaptopView(int laptopId)
        {
            Laptop? laptop = _laptopRepository.GetItem(laptopId);
            if (laptop != null)
            {
                LaptopViewModel laptopViewModel = new(laptop.ID, laptop.Name, laptop.Type, laptop.Stock,
                    laptop.Price, laptop.ScreenSize, laptop.RAM, laptop.Storage);
                return View(laptopViewModel);
            }
            else
            {
                return NotFound();
            }
        }
    }
}

StockManagement.MVC/Views/Shared/GraphicsCardView.cshtml
@using StockManagement.Shared.Models;
@model GraphicsCardViewModel;
@{
    ViewData["Title"] = "GraphicsCardView";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>@Html.Raw(Model.Name)</h1>
<div>
    <div>
        <img src="/ItemImages/DefaultGraphicsCardImage.png" class="img-fluid col-4" alt="Graphics Card Default">
    </div>
    <div>
        <table class="table">
            <tbody>
                <tr>
                    <th scope="row">ID</th>
                    <td>@Html.DisplayFor(model => model.ID)</td>
                </tr>
                <tr>
                    <th scope="row">Name</th>
                    <td>@Html.DisplayFor(model => model.Name)</td>
                </tr>
                <tr>
                    <th scope="row">Type</th>
                    <td>@Html.DisplayFor(model => model.Type)</td>
                </tr>
                <tr>
                    <th scope="row">Stock</th>
                    <td>@Html.DisplayFor(model => model.Stock)</td>
                </tr>
                <tr>
                    <th scope="row">Price</th>
                    <td>£@Html.DisplayFor(model => model.Price)</td>
                </tr>
                <tr>
                    <th scope="row">VRAM</th>
                    <td>@Html.DisplayFor(model => model.VRAM) GB</td>
                </tr>
                <tr>
                    <th scope="row">Cuda Cores</th>
                    <td>@Html.DisplayFor(model => model.CudaCores)</td>
                </tr>
            </tbody>
        </table>
        <div>
            <a class="btn btn-outline-danger" asp-action="DeleteItemView" asp-controller="DeleteItem" asp-route-itemId="@Model.ID">Delete</a>
            <a class="btn btn-outline-warning" asp-action="EditGraphicsCardView" asp-controller="EditGraphicsCard" asp-route-graphicsCardId="@Model.ID">Edit</a>
        </div>
    </div>
</div>

StockManagement.MVC/Views/Shared/LaptopView.cshtml
@using StockManagement.Shared.Models;
@model LaptopViewModel;
@{
    ViewData["Title"] = "LaptopView";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>@Html.Raw(Model.Name)</h1>
<div>
    <div>
        <img src="/ItemImages/DefaultLaptopImage.png" class="img-fluid col-4" alt="Laptop Default">
    </div>
    <div>
        <table class="table">
            <tbody>
                <tr>
                    <th scope="row">ID</th>
                    <td>@Html.DisplayFor(model => model.ID)</td>
                </tr>
                <tr>
                    <th scope="row">Name</th>
                    <td>@Html.DisplayFor(model => model.Name)</td>
                </tr>
                <tr>
                    <th scope="row">Type</th>
                    <td>@Html.DisplayFor(model => model.Type)</td>
                </tr>
                <tr>
                    <th scope="row">Stock</th>
                    <td>@Html.DisplayFor(model => model.Stock)</td>
                </tr>
                <tr>
                    <th scope="row">Price</th>
                    <td>£@Html.DisplayFor(model => model.Price)</td>
                </tr>
                <tr>
                    <th scope="row">Screen Size</th>
                    <td>@Html.DisplayFor(model => model.ScreenSize) Inches</td>
                </tr>
                <tr>
                    <th scope="row">RAM</th>
                    <td>@Html.DisplayFor(model => model.RAM) GB</td>
                </tr>
                <tr>
                    <th scope="row">Storage</th>
                    <td>@Html.DisplayFor(model => model.Storage) GB</td>
                </tr>
            </tbody>
        </table>
        <div>
            <a class="btn btn-outline-danger" asp-action="DeleteItemView" asp-controller="DeleteItem" asp-route-itemId="@Model.ID">Delete</a>
            <a class="btn btn-outline-warning" asp-action="EditLaptopView" asp-controller="EditLaptop" asp-route-laptopId="@Model.ID">Edit</a>
        </div>
    </div>
</div>

StockManagement.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StockManagement.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/StockManagement.MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"
                   asp-route-itemRecentlyAdded="false" asp-route-itemRecentlyEdited="false" asp-route-itemRecentlyDeleted="false">StockManagement.MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index"
                               asp-route-itemRecentlyAdded="false" asp-route-itemRecentlyEdited="false" asp-route-itemRecentlyDeleted="false">Inventory</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - StockManagement.MVC - Ethan Lambourne
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>