StockManagement.MVC/Models/HomeViewModel.cs
using StockManagement.Shared.Models;
using StockManagement.Shared.Repos;

namespace StockManagement.MVC.Models
{
    public class HomeViewModel
    {
        public HomeViewModel(List<Laptop> LaptopList, List<GraphicsCard> GraphicsCardList, bool itemRecentlyAdded, bool itemRecentlyEdited, bool itemRecentlyDeleted)
        {
            this.LaptopList = LaptopList;
            this.GraphicsCardList = GraphicsCardList;
            this.itemRecentlyAdded = itemRecentlyAdded;
            this.itemRecentlyEdited = itemRecentlyEdited;
            this.itemRecentlyDeleted = itemRecentlyDeleted;
        }

        public List<Laptop> LaptopList { get; set; }

        public List<GraphicsCard> GraphicsCardList { get; set; }

        public bool itemRecentlyAdded { get; set; }

        public bool itemRecentlyEdited { get; set; }

        public bool itemRecentlyDeleted { get; set; }
    }
}

StockManagement.MVC/Controllers/AddItemController.cs
using Microsoft.AspNetCore.Mvc;
using StockManagement.MVC.Models;
using StockManagement.Shared.Models;
using StockManagement.Shared.Repos;
using StockManagement.Shared.GenerateID;

namespace StockManagement.MVC.Controllers
{
    public class AddItemController : Controller
    {
        private readonly IItemsRepository<Laptop> _laptopRepository;
        private readonly IItemsRepository<GraphicsCard> _graphicsCardRepository;
        private readonly IGenerateID _generateItemID;

        public AddItemController(IItemsRepository<Laptop> laptopRepository,
            IItemsRepository<GraphicsCard> graphicsCardRepository, IGenerateID generateItemID)
        {
            _laptopRepository = laptopRepository;
            _graphicsCardRepository = graphicsCardRepository;
            _generateItemID = generateItemID;
        }

        [Route("/AddItemForm")]
        public IActionResult AddItemView()
        {
            AddItemViewModel addItemViewModel = new()
            {
                ID = _generateItemID.GenerateID()
            };
            return View(addItemViewModel);
        }

        public IActionResult AddLaptop(int ID, string Name, string Type, int? Stock, double? Price, double ScreenSize, int RAM, int Storage)
        {
            Laptop laptop = new(ID, Name, Type, Stock, Price, ScreenSize, RAM, Storage);
            var addedLaptop = _laptopRepository.AddItem(laptop);
            if (addedLaptop.ID == laptop.ID)
            {
                return RedirectToAction("Index", "Home", new { itemRecentlyAdded = true, itemRecentlyEdited = false, itemRecentlyDeleted = false });
            }
            else
            {
                return BadRequest();
            }
        }

        public IActionResult AddGraphicsCard(int ID, string Name, string Type, int? Stock, double? Price, int VRAM, int CudaCores)
        {
            GraphicsCard graphicsCard = new(ID, Name, Type, Stock, Price, VRAM, CudaCores);
            var addedGraphicsCard = _graphicsCardRepository.AddItem(graphicsCard);
            if (addedGraphicsCard.ID == graphicsCard.ID)
            {
                return RedirectToAction("Index", "Home", new { itemRecentlyAdded = true, itemRecentlyEdited = false, itemRecentlyDeleted = false });
            }
            else
            {
                return BadRequest();
            }
        }
    }
}

StockManagement.MVC/Controllers/GraphicsCardController.cs
using Microsoft.AspNetCore.Mvc;
using StockManagement.MVC.Models;
using StockManagement.Shared.Models;
using StockManagement.Shared.Repos;

namespace StockManagement.MVC.Controllers
{
    public class GraphicsCardController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IItemsRepository<GraphicsCard> _graphicsCardRepository;

        public GraphicsCardController(ILogger<HomeController> logger, IItemsRepository<GraphicsCard> graphicsCardRepository)
        {
            _logger = logger;
            _graphicsCardRepository = graphicsCardRepository;
        }

        [Route("/GraphicsCardDetails/{graphicsCardId}")]
        public IActionResult GraphicsCardView(int graphicsCardId)
        {
            GraphicsCard? graphicsCard = _graphicsCardRepository.GetItem(graphicsCardId);
            if (graphicsCard != null)
            {
                GraphicsCardViewModel graphicsCardViewModel = new(graphicsCard.ID, graphicsCard.Name, graphicsCard.Type, graphicsCard.Stock,
                    graphicsCard.Price, graphicsCard.VRAM, graphicsCard.CudaCores);
                return View(graphicsCardViewModel);
            }
            else
            {
                return NotFound();
            }
        }
    }
}

StockManagement.MVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using StockManagement.MVC.Models;
using System.Diagnostics;
using StockManagement.Shared.Models;
using StockManagement.Shared.Repos;

namespace StockManagement.MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IItemsRepository<Laptop> _laptopRepository;
        private readonly IItemsRepository<GraphicsCard> _graphicsCardRepository;

        public HomeController(ILogger<HomeController> logger, IItemsRepository<Laptop> laptopRepository, IItemsRepository<GraphicsCard> graphicsCardRepository)
        {
            _logger = logger;
            _laptopRepository = laptopRepository;
            _graphicsCardRepository = graphicsCardRepository;
        }

        public IActionResult Index(bool itemRecentlyAdded, bool itemRecentlyEdited, bool itemRecentlyDeleted)
        {
            HomeViewModel homeViewModel = new(_laptopRepository.GetAllItems(), _graphicsCardRepository.GetAllItems(),
                itemRecentlyAdded, itemRecentlyEdited, itemRecentlyDeleted);
            return View(homeViewModel);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

StockManagement.MVC/Controllers/LaptopController.cs
using Microsoft.AspNetCore.Mvc;
using StockManagement.MVC.Models;
using StockManagement.Shared.Models;
using StockManagement.Shared.Repos;

namespace StockManagement.MVC.Controllers
{
    public class LaptopController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IItemsRepository<Laptop> _laptopRepository;

        public LaptopController(ILogger<HomeController> logger, IItemsRepository<Laptop> laptopRepository)
        {
            _logger = logger;
            _laptopRepository = laptopRepository;
        }

        [Route("/LaptopDetails/{laptopId}")]
        public IActionResult LaptopView(int laptopId)
        {
            Laptop? laptop = _laptopRepository.GetItem(laptopId);
            if (laptop != null)
            {
                LaptopViewModel laptopViewModel = new(laptop.ID, laptop.Name, laptop.Type, laptop.Stock,
                    laptop.Price, laptop.ScreenSize, laptop.RAM, laptop.Storage);
                return View(laptopViewModel);
            }
            else
            {
                return NotFound();
            }
        }
    }
}

StockManagement.MVC/Views/Home/Index.cshtml
@using StockManagement.MVC.Controllers;
@using StockManagement.MVC.Models;
@using StockManagement.Shared.Models;
@using StockManagement.Shared.Repos;
@model HomeViewModel;
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    @{
        if (Model.itemRecentlyAdded)
        {
            <div class="alert alert-success">
                Item Added
            </div>
        }
        if (Model.itemRecentlyEdited)
        {
            <div class="alert alert-warning">
                Item Edited
            </div>
        }
        if (Model.itemRecentlyDeleted)
        {
            <div class="alert alert-danger">
                Item Deleted
            </div>
        }
    }
    <h1 class="display-4">Inventory</h1>
    <p>Search through the store inventory and select items.</p>

    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Item Type</th>
                <th>Stock</th>
                <th>Price</th>
                <th><a class="btn btn-outline-success" asp-action="AddItemView" asp-controller="AddItem">Add New Item</a></th>
            </tr>
        </thead>
        <tbody>
            @{
                List<Items> itemList = new();
                itemList.AddRange(Model.LaptopList);
                itemList.AddRange(Model.GraphicsCardList);
                var sortedItemList = itemList.OrderBy(item => item.ID).ToList();
                foreach (var item in sortedItemList)
                {
                    <tr>
                        <th scope="row">@Html.Raw(item.ID)</th>
                        <td>@Html.Raw(item.Name)</td>
                        <td>@Html.Raw(item.Type)</td>
                        <td>@Html.Raw(item.Stock)</td>
                        <td>£@string.Format("{0:#,##0.##}", item.Price)</td>
                        @{
                            if (item.Type == "laptop")
                            {
                                <td><a class="btn btn-outline-info" asp-action="LaptopView" asp-controller="Laptop" asp-route-laptopId="@item.ID">Info</a></td>
                            }
                            if (item.Type == "graphics card")
                            {
                                <td><a class="btn btn-outline-info" asp-action="GraphicsCardView" asp-controller="GraphicsCard" asp-route-graphicsCardId="@item.ID">Info</a></td>
                            }
                        }
                    </tr>
                }
            }
        </tbody>
        
    </table>

</div>